include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_relative_imports: true
    sort_child_properties_last: false

analyzer:
  exclude:
    - lib/generated/**
    - lib/**/*.g.dart
    - lib/**/*.freezed.dart

