name: afcm_app
description: AFCM event progressive web application
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.19.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  go_router: ^14.2.1
  flutter_riverpod: ^2.5.1
  supabase_flutter: ^2.3.4
  dio: ^5.4.2+1
  intl: ^0.19.0
  qr_flutter: ^4.1.0
  flutter_web_plugins:
    sdk: flutter
  url_launcher: ^6.2.5
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.9
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  generate: true
