name: afcm_web
description: AFCM event progressive web app – Module 1 (registration & tickets)
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: '>=3.22.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  go_router: ^13.2.0
  flutter_riverpod: ^2.4.9
  supabase_flutter: ^2.5.6
  dio: ^5.4.3
  intl: '>=0.19.0 <0.21.0'
  qr_flutter: ^4.1.0
  url_launcher: ^6.3.0
  shared_preferences: ^2.2.2
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  logging: ^1.2.0
  collection: ^1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.9
  freezed: ^2.4.7
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
